Fixed deployment issues after modularization (#94)
* moved notebooks to notebooks/

* added requirement.txt

* updated app.py for deployment: debug=False, server = app.server

* attempt 1 to fix ModuleNotFoundError: No module named 'callbacks'

* attempt 2 to fix ModuleNotFoundError: No module named 'callbacks'

* attempt 1 to fix ImportError: cannot import name 'alt_data' from 'data'

* added __init__.py

* modified import lines so it can both run on locally and render.com; set app.run(debug=False)

* updated readme for new instruction